-- Drop tables
DROP TABLE TB_HISTORICO_DENTAL CASCADE CONSTRAINTS;
DROP TABLE TB_PROCEDIMENTO_DENTARIO CASCADE CONSTRAINTS;
DROP TABLE TB_DADO_MONITORAMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_RELATO_PROBLEMA_DENTARIO CASCADE CONSTRAINTS;
DROP TABLE TB_ANALISE_DENTARIA CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO CASCADE CONSTRAINTS;
DROP TABLE TB_ANALISE_DENTARIA_DADO_MONITORAMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_AUDITORIA CASCADE CONSTRAINTS;

-- Create tables
CREATE TABLE TB_USUARIO
(
    ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME   VARCHAR2(120) NOT NULL,
    EMAIL  VARCHAR2(120) NOT NULL UNIQUE,
    SENHA  VARCHAR2(255) NOT NULL,
    GENERO CHAR(1)       NOT NULL
);

CREATE TABLE TB_ANALISE_DENTARIA
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    DATA_ANALISE DATE NOT NULL,
    PROBABILIDADE_PROBLEMA NUMBER(5,2) NOT NULL,
    CONSTRAINT FK_ANALISE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE TB_DADO_MONITORAMENTO
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    CONSTRAINT FK_MONITORAMENTO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE TB_RELATO_PROBLEMA_DENTARIO
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY  PRIMARY KEY,
    ID_DADO_MONITORAMENTO INTEGER NOT NULL,
    PROBLEMA VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_RELATO_PROBLEMA_DENTARIO_ID_DADO_MONITORAMENTO FOREIGN KEY (ID_DADO_MONITORAMENTO) REFERENCES TB_DADO_MONITORAMENTO(ID) ON DELETE CASCADE
);


CREATE TABLE TB_ANALISE_DENTARIA_DADO_MONITORAMENTO
(
    ID_ANALISE_DENTARIA INTEGER NOT NULL,
    ID_DADO_MONITORAMENTO INTEGER NOT NULL,
    PRIMARY KEY (ID_ANALISE_DENTARIA, ID_DADO_MONITORAMENTO),
    FOREIGN KEY (ID_ANALISE_DENTARIA) REFERENCES TB_ANALISE_DENTARIA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_DADO_MONITORAMENTO) REFERENCES TB_DADO_MONITORAMENTO(ID) ON DELETE CASCADE
);

CREATE TABLE TB_HISTORICO_DENTAL
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    CONDICAO_DENTE VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_HISTORICO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE TB_PROCEDIMENTO_DENTARIO
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_HISTORICO_DENTAL INTEGER NOT NULL,
    PROCEDIMENTO VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_PROCEDIMENTO_DENTARIO_ID_HISTORICO_DENTAL FOREIGN KEY (ID_HISTORICO_DENTAL) REFERENCES TB_HISTORICO_DENTAL(ID) ON DELETE CASCADE
);

CREATE TABLE TB_AUDITORIA (
    ID_AUDITORIA INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABELA VARCHAR2(50) NOT NULL,
    OPERACAO VARCHAR2(10) NOT NULL,
    ID_REGISTRO INTEGER NOT NULL,
    USUARIO VARCHAR2(50) NOT NULL,
    DATA_OPERACAO TIMESTAMP NOT NULL,
    VALOR_ANTIGO CLOB,
    VALOR_NOVO CLOB
);